insert into secretaria values('17167', 'Caio Petrucci dos Santos Rosa', 'U2VuaGExMjM=')
insert into secretaria values('17164', 'Artur de Paula Morais', 'U2VuaGExMjM=')

insert into especialidade values('Pediatria')
insert into especialidade values('Cardiologia')
insert into especialidade values('Oftalmologia')
insert into especialidade values('Geriatria')
insert into especialidade values('Odontologia')
insert into especialidade values('Neurologia')
insert into especialidade values('Ginecologia')

insert into exame ('Coagulograma')
insert into exame ('Densitometria Óssea')
insert into exame ('Dismorfismo Eritrocitário')
insert into exame ('Doppler Transcraniano')
insert into exame ('Ecocardiograma')
insert into exame ('Eletrocardiograma')
insert into exame ('Eletroencefalograma')
insert into exame ('Eletronistagmografia')
insert into exame ('Endoscopia Digestiva')
insert into exame ('Espermograma')
insert into exame ('Exame de Fezes')
insert into exame ('Exame de próstata')
insert into exame ('Exame de Sangue')
insert into exame ('Exame Físico')
insert into exame ('Exame Psicotécnico')
insert into exame ('Exame Toxicológico')
insert into exame ('Exames Antidoping')
insert into exame ('Fetoscopia')
insert into exame ('Hemocultura')
insert into exame ('Hemograma')
insert into exame ('Imuno-histoquímica')
insert into exame ('Imunofluorescência')