insert into secretaria values('17167', 'Caio Petrucci dos Santos Rosa', 'U2VuaGExMjM=')
insert into secretaria values('17164', 'Artur de Paula Morais', 'U2VuaGExMjM=')

insert into especialidade values('Pediatria')
insert into especialidade values('Cardiologia')
insert into especialidade values('Oftalmologia')
insert into especialidade values('Geriatria')
insert into especialidade values('Odontologia')
insert into especialidade values('Neurologia')
insert into especialidade values('Ginecologia')

insert into exame values('Coagulograma')
insert into exame values('Densitometria Óssea')
insert into exame values('Dismorfismo Eritrocitário')
insert into exame values('Doppler Transcraniano')
insert into exame values('Ecocardiograma')
insert into exame values('Eletrocardiograma')
insert into exame values('Eletroencefalograma')
insert into exame values('Eletronistagmografia')
insert into exame values('Endoscopia Digestiva')
insert into exame values('Espermograma')
insert into exame values('Exame de Fezes')
insert into exame values('Exame de próstata')
insert into exame values('Exame de Sangue')
insert into exame values('Exame Físico')
insert into exame values('Exame Psicotécnico')
insert into exame values('Exame Toxicológico')
insert into exame values('Exames Antidoping')
insert into exame values('Fetoscopia')
insert into exame values('Hemocultura')
insert into exame values('Hemograma')
insert into exame values('Imuno-histoquímica')
insert into exame values('Imunofluorescência')